---
- name: Install Backstage on Ubuntu server
  hosts: backstage

  tasks:
    # sudo apt update && sudo apt upgrade -y
    - name: Apt update/upgrade
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "*"
        state: latest

    # sudo apt install -y make build-essential
    - name: Install pre-requisites
      become: true
      apt:
        name:
          - curl
          - make
          - build-essential
          - git
        state: present

    # github.com/nvm-sh/nvm?tab=readme-ov-file#ansible
    # https://github.com/nvm-sh/nvm?tab=readme-ov-file#install--update-script
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Install Node.js and yarn
      ansible.builtin.shell: |
        . {{ ansible_env.HOME }}/.nvm/nvm.sh
        nvm install --lts
        npm install --global yarn
      args:
        executable: /bin/bash
        chdir: "{{ansible_env.HOME}}"

    # TODO: Improve this
    # sudo apt install docker.io
    - name: Install docker(.io)
      become: true
      apt:
        name:
          - docker.io
        state: present

    # Enable ports 3000 and 7007
    - name: Allow ports 3000 & 7007
      become: true
      community.general.ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - 3000
        - 7007

    # TODO
    # - Add configuration of .vimrc, .bashrc

# -------------------------------------------------------------------

# curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash 
#    - name: Fetch nvm
#      ansible.builtin.uri:
#        url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh
#        return_content: yes
#      register: nvm_installer
#
#    - name: Debug NVM installer content
#      ansible.builtin.debug:
#        msg: "{{ nvm_installer.content }}"
#
#    - name: Run nvm installer
#      ansible.builtin.shell:
#        cmd: "bash -s"
#        stdin: "{{ nvm_installer.content }}"